import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Manrope, Cormorant_Garamond } from "next/font/google";

import "./globals.css";
import Navbar from "@/components/Navbar";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const garamond = Cormorant_Garamond({
  variable: "--font-garamond",
  subsets: ["latin"],
});

export const metadata = {
  title: "AISA",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const messages = await getMessages();

  return (
    <NextIntlClientProvider messages={messages}>
      <html lang="en">
        <body
          className={`${manrope.variable} ${garamond.variable} antialiased`}
        >
          <Navbar />
          {children}
        </body>
      </html>
    </NextIntlClientProvider>
  );
}
